apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8nfig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8nfig
  template:
    metadata:
      labels:
        app: k8nfig
    spec:
      containers:
        - name: k8nfig
          image: charmingruby/k8nfig:0.3.0
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_NAME
              value: "k8nfig"
            - name: APP_VERSION
              value: "0.3.0"
            - name: APP_AUTHOR
              value: "gustavo dias"
---
apiVersion: v1
kind: Service
metadata:
  name: k8nfig
spec:
  selector:
    app: k8nfig
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000 # port to be used by port binding
  type: NodePort
